[versions]
accompanistPager = "0.22.0-rc"
accompanistPermissions = "0.31.2-alpha"
agp = "8.9.1"
coilCompose = "2.2.1"
coilComposeVersion = "2.2.1"
converterGson = "2.11.0"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
desugar_jdk_libs = "2.1.5"
enumSupport = "2.10.0"
espressoCore = "3.6.1"
gsonSupport = "2.10.0"
gsonVersion = "2.11.0"
hilt = "2.51.1"
hiltCommon = "1.2.0"
hiltNavigationCompose = "1.2.0"
kotlin = "2.0.0"
ksp = "2.0.0-1.0.23"
kotlinxCoroutinesCore = "1.8.0"
kotlinxCoroutinesAndroid = "1.8.0"
kotpref = "2.10.0"
initializer = "2.10.0"
lifecycleRuntimeKtx = "2.8.7"
lifecycleLivedataKtx = "2.8.7"
lifecycleRuntimeKtxVersion = "2.8.7"
lifecycleViewmodelSavedstate = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
livedataSupport = "2.10.0"
composeBom = "2024.09.00"
material3 = "1.3.2"
material3Android = "1.3.2"
navigationCompose = "2.8.9"
okhttp = "5.0.0-alpha.2"
okhttpUrlconnection = "5.0.0-alpha.2"
activityCompose = "1.10.1"
constraintlayoutCompose = "1.1.1"
playServicesAds = "24.5.0"
preferenceKtx = "1.2.1"
retrofit = "2.11.0"
roomKtx = "2.7.1"
roomRuntime = "2.7.1"

uiTestAndroid = "1.8.0"
animationCoreAndroid = "1.8.0"
foundationAndroid = "1.8.0"
preferenceScreenDsl = "2.10.0"
loggingInterceptor = "5.0.0-alpha.2"
multidex = "2.0.1"
unityAds = "4.14.1"
workRuntimeKtx = "2.10.1"





[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanistPager" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx-v251 = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtxVersion" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-runtime = { module = "androidx.compose.runtime:runtime" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
foundation = { module = "androidx.compose.foundation:foundation" }
foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleViewmodelSavedstate" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
gson-support = { module = "com.chibatching.kotpref:gson-support", version.ref = "gsonSupport" }
androidx-animation-core-android = { group = "androidx.compose.animation", name = "animation-core-android", version.ref = "animationCoreAndroid" }
androidx-foundation-android = { group = "androidx.compose.foundation", name = "foundation-android", version.ref = "foundationAndroid" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-ui-test-android = { group = "androidx.compose.ui", name = "ui-test-android", version.ref = "uiTestAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotpref = { module = "com.chibatching.kotpref:kotpref", version.ref = "kotpref" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
initializer = { module = "com.chibatching.kotpref:initializer", version.ref = "initializer" }
enum-support = { module = "com.chibatching.kotpref:enum-support", version.ref = "enumSupport" }
livedata-support = { module = "com.chibatching.kotpref:livedata-support", version.ref = "livedataSupport" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
playservices-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
preference-screen-dsl = { module = "com.chibatching.kotpref:preference-screen-dsl", version.ref = "preferenceScreenDsl" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-compose-v210 = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
okhttp-urlconnection = { module = "com.squareup.okhttp3:okhttp-urlconnection", version.ref = "okhttpUrlconnection" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
unity-ads = { module = "com.unity3d.ads:unity-ads", version.ref = "unityAds" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }










[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }



